---
# Defaults can be found at https://jekyllrb.com/docs/configuration/default/

baseurl: /stars
description: Background information about Github repositories I have starred.
permalink: /:year/:title/
remote_theme: Potherca/extend-the-docs@theme
repository: potherca/stars
timezone: Europe/Amsterdam
title: Potherca's Weekly Github Stars

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      toc: true
  -
    scope:
      path: "repos"
    values:
      layout: post

plugins:
  - jekyll-archives
  - jekyll-tidy
  - jekyll-toc

  # - jekyll-avatar
  # - jekyll-commonmark-ghpages
  # NOT YET COMPATIBLE # - jekyll-default-layout
  # - jekyll-feed
  # - jekyll-gist
  # - jekyll-github-metadata
  # - jekyll-mentions
  # - jekyll-optional-front-matter
  # - jekyll-paginate
  # - jekyll-readme-index
  # - jekyll-redirect-from
  # - jekyll-relative-links
  # - jekyll-remote-theme
  # - jekyll-seo-tag
  # - jekyll-sitemap
  # - jekyll-titles-from-headings

# Plugin specific settings
jekyll-archives:
  enabled: [year, categories, tags]

# Extend the Docs (Fork) settings
nav:
  exclude:
    - "/"
  recurse: true
  cross_repository:
    show_homepage: false # use the homepage (from the repository settings) instead of https://site.url/repository-name
    show_archived: false  # Whether to include repositories that have been archived (true) or not (false)

# Just the Docs (Source) settings
aux_links:
  "Potherca on GitHub":
    - "https://github.com/Potherca"

gh_edit_repository: https://github.com/Potherca/liquid-linter-cli
